name: sitepackage/tech-badge-list
typeName: sitepackage_tech_badge_list
group: default
prefixFields: true
prefixType: full
fields:
  -
    identifier: groups
    type: Collection
    label: 'Groups (e.g. ENV.CORE, ENV.FRONTEND, ENV.TOOLS, ENV.INTEGRATION)'
    labelField: group_label
    minitems: 1
    fields:
      -
        identifier: group_label
        type: Text
        label: 'Group label'
        placeholder: 'e.g. ENV.CORE'
      -
        identifier: badges
        type: Collection
        label: Badges
        labelField: label
        minitems: 1
        fields:
          -
            identifier: label
            type: Text
            label: Badge
            placeholder: 'e.g. TYPO3 v13, PHP 8.x'
